# Generated by Django 4.0.5 on 2022-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_usuarios_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
